version: 1.1.0-{build}
image: Visual Studio 2015
build_script:
- cmd: >-
    move BaseNEncodings SapientGuardian.BaseNEncodings

    dotnet restore -v Warning	

    dotnet pack .\SapientGuardian.BaseNEncodings -o .\artifacts\SapientGuardian.BaseNEncodings -c Release
artifacts:
- path: 'artifacts\**\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: 7nX5a7V6wWbtPSJ6bQSU9BRZwJEdn70w0Ydlf5fuk44Gjk9BVgxnYK6u8MNzT2yA
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true